### ISSUE TITLE
rake resque:pool does not start in the background

### ISSUE THREAD

**Issue by john-999** [nevans/resque-pool#103]
resque-pool does not start in the background when launched via the rake task:
```
$ TERM_CHILD=1 PIDFILE=./tmp/pids/resque-pool.pid BACKGROUND=yes rake resque:pool
```

**Comment by nevans** [comment]
resque-pool lives in a weird place where it uses rake tasks for config *and* it has its own binary.  I did it this because the official resque README encouraged using rake for config so I built on that.  But really, you ought to simply use the `resque-pool` executable for running it.  Running resque-pool from rake is a neat trick, but will *not* be fully supported.  :)
