### ISSUE TITLE
Is this forking or spawn multiple processes?

### ISSUE THREAD

**Issue by phuongnd08** [nevans/resque-pool#133]
I'm confused: is this resque pool forking multiple resque workers from a single rails application process or is it starting multiple rails application in parallel? The former sounds efficient.

**Comment by nevans** [comment]
`resque-pool` forks multiple processes.  It does not exec in the child processes, so anything loaded in the parent process will still be loaded in the child processes.  With copy-on-write-friendly GC in ruby 2.0+'s (or REE 1.8), you should also save on total memory usage.

It's up to you to make sure that your application (rails or otherwise) is loaded in the parent process and reload any IO resources that are unsafe to share between processes.  If you follow the [documentation in resque-pool's README](https://github.com/nevans/resque-pool#rake-task-config) to load `:environment` from `rake resque:setup` (which runs in the parent process) and reconnect shared DB connections (in the child processes), then this ought to work efficiently.

**Comment by phuongnd08** [comment]
Thank you. This would make an excellent choice on Heroku.

**Comment by nevans** [comment]
https://devcenter.heroku.com/articles/ruby-resque-pool should get you started.  Don't forget to set `TERM_CHILD`

**Comment by phuongnd08** [comment]
Excellent, thank you.
